project:
  type: website
  resources: docs/

website:
  title: "James Ritchie"
  search: false
  navbar: false
  favicon: favicon.ico
  page-footer: "Built with [Quarto](https://quarto.org/)."
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: mathml
    minimal: true
    include-in-header: goatcounter.html



